import numpy as np
from pups_inference import load_model, delta_report

# 真实序列：同一个蛋白的野生型 vs 单点突变型（从你的 Cell 2024 数据里取）
WT = "MELDFGHFDERDKTSRNMRGSRMNGLPSPTHSAHCSFYRTRTLQALSNEKKAKKVRFYRNGDRYFKGIVYAVSSDRFRSFDALLADLTRSLSDNINLPQGVRYIYTIDGSRKIGSMDELEEGESYVCSSDNFFKKVEYTKNVNPNWSVNVKTSANMKAPQSLASSNSAQARENKDFVRPKLVTIIRSGVKPRKAVRVLLNKKTAHSFEQVLTDITEAIKLETGVVKKLYTLDGKQVTCLHDFFGDDDVFIACGPEKFRYAQDDFSLDENECRVMKGNPSATAGPKASPTPQKTSAKSPGPMRRSKSPADSGNDQDANGTSSSQLSTPKSKQSPISTPTSPGSLRKHKDLYLPLSLDDSDSLGDSM"
MT = "MELDFGHFDERDKTSRNMRGSRMNGLPSPTHSAHCSFYRTRTLQALRNEKKAKKVRFYRNGDRYFKGIVYAVSSDRFRSFDALLADLTRSLSDNINLPQGVRYIYTIDGSRKIGSMDELEEGESYVCSSDNFFKKVEYTKNVNPNWSVNVKTSANMKAPQSLASSNSAQARENKDFVRPKLVTIIRSGVKPRKAVRVLLNKKTAHSFEQVLTDITEAIKLETGVVKKLYTLDGKQVTCLHDFFGDDDVFIACGPEKFRYAQDDFSLDENECRVMKGNPSATAGPKASPTPQKTSAKSPGPMRRSKSPADSGNDQDANGTSSSQLSTPKSKQSPISTPTSPGSLRKHKDLYLPLSLDDSDSLGDSM"


def find_mutation_pos(wt_seq, mt_seq):
    """Return the 1-indexed position where wt_seq and mt_seq first differ."""
    for i, (a, b) in enumerate(zip(wt_seq, mt_seq)):
        if a != b:
            return i + 1
    return None


lm = np.load("/mnt/volume6/czj/labLGN/LabLZ/pups_trial/real_landmark.npy")
model = load_model()
print("device:", next(model.parameters()).device)
pos = find_mutation_pos(WT, MT)
print("mutation position:", pos)
d = delta_report(model, WT, MT, lm, pos=pos)
